apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: my-app
    backend: spring
spec:
  selector:
    matchLabels:
      app: my-app
      backend: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
        backend: spring
    spec:
      containers:
        - name: spring
          image: fcusco96/api-rest:v3
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: my-app
    backend: spring
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
  selector:
    app: my-app
    backend: spring